#!/usr/bin/env python3
"""Import published WordPress blog posts into the static Salmon HVAC site."""

from __future__ import annotations

import html
import json
import math
import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional


ROOT = Path(__file__).resolve().parent.parent
SQL_PATH = ROOT / "tmp" / "wpress-extract" / "database.sql"
UPLOADS_ROOT = ROOT / "tmp" / "wpress-extract" / "uploads"
BLOG_ROOT = ROOT / "blog"
POSTS_JSON_PATH = BLOG_ROOT / "posts.json"
BLOG_INDEX_PATH = BLOG_ROOT / "index.html"
IMAGE_DEST_ROOT = ROOT / "assets" / "images" / "blog" / "wordpress"
BASE_URL = "https://salmonhvac.com"
GENERATED_MARKER = "<!-- Generated by scripts/import-wordpress-blog.py -->"


def split_sql_tuples(values_blob: str) -> List[List[str]]:
    tuples: List[List[str]] = []
    i = 0
    length = len(values_blob)

    while i < length:
        if values_blob[i] != "(":
            i += 1
            continue

        i += 1
        current = []
        field: List[str] = []
        in_string = False
        escaped = False

        while i < length:
            char = values_blob[i]

            if in_string:
                field.append(char)
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == "'":
                    in_string = False
                i += 1
                continue

            if char == "'":
                in_string = True
                field.append(char)
                i += 1
                continue

            if char == ",":
                current.append("".join(field).strip())
                field = []
                i += 1
                continue

            if char == ")":
                current.append("".join(field).strip())
                tuples.append(current)
                i += 1
                break

            field.append(char)
            i += 1

        while i < length and values_blob[i] in ", \n\r\t":
            i += 1

    return tuples


def parse_sql_value(raw: str):
    if raw == "NULL":
        return None

    if raw.startswith("'") and raw.endswith("'"):
        value = raw[1:-1]
        value = (
            value.replace("\\\\", "\\")
            .replace("\\'", "'")
            .replace('\\"', '"')
            .replace("\\/", "/")
            .replace("\\n", "\n")
            .replace("\\r", "\r")
            .replace("\\0", "\x00")
        )
        return value

    try:
        return int(raw)
    except ValueError:
        return raw


def parse_insert_rows(table_name: str, text: str) -> Iterable[List[object]]:
    pattern = re.compile(rf"INSERT INTO `{table_name}` VALUES\s*(.+?);\n", re.S)
    for match in pattern.finditer(text):
        for row in split_sql_tuples(match.group(1)):
            yield [parse_sql_value(value) for value in row]


def load_wordpress_data() -> tuple[List[dict], Dict[int, Dict[str, List[object]]]]:
    sql = SQL_PATH.read_text("utf-8", errors="replace")

    posts = []
    for row in parse_insert_rows("SERVMASK_PREFIX_posts", sql):
        if len(row) < 23:
            continue
        posts.append(
            {
                "ID": row[0],
                "post_author": row[1],
                "post_date": row[2],
                "post_date_gmt": row[3],
                "post_content": row[4] or "",
                "post_title": row[5] or "",
                "post_excerpt": row[6] or "",
                "post_status": row[7],
                "comment_status": row[8],
                "ping_status": row[9],
                "post_name": row[11] or "",
                "post_modified": row[14],
                "post_modified_gmt": row[15],
                "guid": row[18] or "",
                "post_type": row[20],
                "post_parent": row[21],
            }
        )

    postmeta: Dict[int, Dict[str, List[object]]] = {}
    for row in parse_insert_rows("SERVMASK_PREFIX_postmeta", sql):
        if len(row) < 4:
            continue
        post_id = int(row[1])
        meta_key = row[2]
        meta_value = row[3]
        postmeta.setdefault(post_id, {}).setdefault(meta_key, []).append(meta_value)

    return posts, postmeta


def clean_text(value: str) -> str:
    text = re.sub(r"<[^>]+>", " ", value or "")
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    return text


def clean_html_content(content: str) -> str:
    cleaned = content or ""
    cleaned = re.sub(r"<!--\s*wp:[\s\S]*?-->", "", cleaned)
    cleaned = re.sub(r"<!--\s*/wp:[\s\S]*?-->", "", cleaned)
    cleaned = re.sub(r"\[/?caption[^\]]*\]", "", cleaned)
    cleaned = re.sub(r"<script[\s\S]*?</script>", "", cleaned, flags=re.I)
    cleaned = re.sub(r"<style[\s\S]*?</style>", "", cleaned, flags=re.I)
    cleaned = re.sub(r'\s+class="[^"]*"', "", cleaned)
    cleaned = re.sub(r'\s+id="[^"]*"', "", cleaned)
    cleaned = re.sub(r"\s+data-[a-zA-Z0-9_-]+=\"[^\"]*\"", "", cleaned)
    cleaned = re.sub(r"\s+aria-label=\"[^\"]*\"", "", cleaned)
    cleaned = cleaned.replace("\r", "")
    cleaned = rewrite_site_urls(cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).strip()
    return cleaned


def first_paragraph_text(content: str) -> str:
    paragraph_match = re.search(r"<p[^>]*>(.*?)</p>", content, re.I | re.S)
    if paragraph_match:
        return clean_text(paragraph_match.group(1))
    return clean_text(content)


def excerpt_from_content(content: str, limit: int = 180) -> str:
    text = first_paragraph_text(content)
    if len(text) <= limit:
        return text
    shortened = text[: limit + 1]
    if " " in shortened:
        shortened = shortened.rsplit(" ", 1)[0]
    return shortened.rstrip(".,;:") + "..."


def slug_from_url(url: str) -> str:
    return url.strip("/").split("/")[-1]


def load_current_posts() -> Dict[str, dict]:
    current_entries = json.loads(POSTS_JSON_PATH.read_text("utf-8"))
    return {slug_from_url(entry["url"]): entry for entry in current_entries}


def current_authoritative_slugs() -> set[str]:
    authoritative = set()
    for path in BLOG_ROOT.glob("*/index.html"):
        if path.parent == BLOG_ROOT:
            continue
        contents = path.read_text("utf-8")
        if GENERATED_MARKER not in contents:
            authoritative.add(path.parent.name)
    return authoritative


def wp_image_path_from_attachment(attachment_id: Optional[int], postmeta: Dict[int, Dict[str, List[object]]]) -> Optional[str]:
    if not attachment_id:
        return None
    attachment_meta = postmeta.get(int(attachment_id), {})
    values = attachment_meta.get("_wp_attached_file", [])
    if values:
        return str(values[0])
    return None


def wp_image_alt(attachment_id: Optional[int], postmeta: Dict[int, Dict[str, List[object]]], fallback: str) -> str:
    if not attachment_id:
        return fallback
    attachment_meta = postmeta.get(int(attachment_id), {})
    alt_values = attachment_meta.get("_wp_attachment_image_alt", [])
    if alt_values and str(alt_values[0]).strip():
        return clean_text(str(alt_values[0]))
    return fallback


def copy_featured_image(relative_path: Optional[str]) -> Optional[str]:
    if not relative_path:
        return None

    source = UPLOADS_ROOT / relative_path
    if not source.exists():
        return None

    destination = IMAGE_DEST_ROOT / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    if not destination.exists():
        shutil.copy2(source, destination)

    return "/" + destination.relative_to(ROOT).as_posix()


def rewrite_site_urls(content: str) -> str:
    content = re.sub(
        r'(href|src)="https?://(?:www\.)?salmonhvac\.com(/[^"]*)"',
        lambda match: f'{match.group(1)}="{match.group(2)}"',
        content,
        flags=re.I,
    )
    content = re.sub(
        r'(href|src)="https?://[^"]*/wp-content/uploads/([^"]+)"',
        lambda match: f'{match.group(1)}="/assets/images/blog/wordpress/{match.group(2)}"',
        content,
        flags=re.I,
    )
    content = re.sub(
        r'(href|src)="/wp-content/uploads/([^"]+)"',
        lambda match: f'{match.group(1)}="/assets/images/blog/wordpress/{match.group(2)}"',
        content,
        flags=re.I,
    )
    return content


def human_date(value: str) -> str:
    return datetime.strptime(value[:10], "%Y-%m-%d").strftime("%B %-d, %Y")


def iso_date(value: str) -> str:
    return value[:10]


def estimate_read_time(content: str) -> str:
    word_count = len(re.findall(r"\b[\w'-]+\b", clean_text(content)))
    minutes = max(1, math.ceil(word_count / 225))
    return f"{minutes} min read"


def escape_attr(value: str) -> str:
    return html.escape(value, quote=True)


def render_post_html(post: dict) -> str:
    title = post["title"]
    excerpt = post["excerpt"]
    slug = post["slug"]
    url = f"/blog/{slug}/"
    canonical = f"{BASE_URL}{url}"
    image_url = post["image"] or "/assets/images/logo-salmon.png"
    absolute_image_url = image_url if image_url.startswith("http") else f"{BASE_URL}{image_url}"
    image_alt = post["imageAlt"]
    published = post["date"]
    modified = post["modified"]
    hero_subtext = post["heroSubtext"]
    body_html = post["content"]
    read_time = post["readTime"]

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){{w[l]=w[l]||[];w[l].push({{'gtm.start':
new Date().getTime(),event:'gtm.js'}});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
}})(window,document,'script','dataLayer','GTM-593W9BPW');</script>
<!-- End Google Tag Manager -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{escape_attr(title)} | Salmon HVAC</title>
  <meta name="description" content="{escape_attr(excerpt)}">
  <link rel="canonical" href="{canonical}">

  <meta property="og:type" content="article">
  <meta property="og:title" content="{escape_attr(title)} | Salmon HVAC">
  <meta property="og:description" content="{escape_attr(excerpt)}">
  <meta property="og:url" content="{canonical}">
  <meta property="og:image" content="{absolute_image_url}">
  <meta property="og:site_name" content="Salmon HVAC">
  <meta property="og:locale" content="en_US">

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{escape_attr(title)} | Salmon HVAC">
  <meta name="twitter:description" content="{escape_attr(excerpt)}">
  <meta name="twitter:image" content="{absolute_image_url}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Orbitron:wght@700;800;900&family=Rajdhani:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/style.css?v=3">
  <link rel="preload" as="image" href="{image_url}">

  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": {json.dumps(title)},
    "description": {json.dumps(excerpt)},
    "author": {{
      "@type": "Organization",
      "@id": "https://salmonhvac.com/#organization",
      "name": "Salmon HVAC",
      "url": "https://salmonhvac.com"
    }},
    "publisher": {{
      "@type": "Organization",
      "@id": "https://salmonhvac.com/#organization",
      "name": "Salmon HVAC",
      "logo": {{
        "@type": "ImageObject",
        "url": "https://salmonhvac.com/assets/images/logo-salmon.png"
      }}
    }},
    "datePublished": "{published}",
    "dateModified": "{modified}",
    "image": "{absolute_image_url}",
    "url": "{canonical}",
    "mainEntityOfPage": {{
      "@type": "WebPage",
      "@id": "{canonical}"
    }},
    "inLanguage": "en-US"
  }}
  </script>

  <script type="application/ld+json">
  {{
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {{"@type": "ListItem", "position": 1, "name": "Home", "item": "https://salmonhvac.com/"}},
      {{"@type": "ListItem", "position": 2, "name": "Blog", "item": "https://salmonhvac.com/blog/"}},
      {{"@type": "ListItem", "position": 3, "name": {json.dumps(title)}, "item": "{canonical}"}}
    ]
  }}
  </script>
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-593W9BPW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

{GENERATED_MARKER}
<!-- PARTIAL:nav:start -->
<header class="header">
  <div class="container">
    <a href="/" class="logo">
      <img src="/assets/images/logo-salmon.png" alt="Salmon HVAC Logo" width="50" height="50">
      <span class="logo-text">Salmon <span>HVAC</span></span>
    </a>

    <nav class="nav-menu" aria-label="Main navigation">
      <a href="/" class="nav-link">Home</a>

      <div class="nav-dropdown">
        <a href="/services/" class="nav-link nav-dropdown-toggle">Services <i class="fas fa-chevron-down" aria-hidden="true"></i></a>
        <div class="dropdown-menu">
          <a href="/services/ac-repair/">AC Repair</a>
          <a href="/services/ac-installation/">AC Installation</a>
          <a href="/services/ac-maintenance/">AC Maintenance</a>
          <a href="/services/furnace-repair/">Furnace Repair</a>
          <a href="/services/furnace-installation/">Furnace Installation</a>
          <a href="/services/heat-pump-services/">Heat Pump Services</a>
          <a href="/services/ductless-mini-split/">Ductless Mini-Split</a>
          <a href="/services/vrf-systems/">VRF Systems</a>
          <a href="/services/commercial-hvac/">Commercial HVAC</a>
          <a href="/services/indoor-air-quality/">Indoor Air Quality</a>
          <a href="/services/emergency-hvac/">Emergency HVAC</a>
        </div>
      </div>

      <div class="nav-dropdown">
        <a href="/areas/" class="nav-link nav-dropdown-toggle">Service Areas <i class="fas fa-chevron-down" aria-hidden="true"></i></a>
        <div class="dropdown-menu">
          <span class="dropdown-group-label">Davis County</span>
          <a href="/areas/centerville-ut/">Centerville</a>
          <a href="/areas/bountiful-ut/">Bountiful</a>
          <a href="/areas/layton-ut/">Layton</a>
          <a href="/areas/kaysville-ut/">Kaysville</a>
          <a href="/areas/farmington-ut/">Farmington</a>
          <a href="/areas/fruit-heights-ut/">Fruit Heights</a>
          <span class="dropdown-group-label">Weber County</span>
          <a href="/areas/ogden-ut/">Ogden</a>
          <a href="/areas/clearfield-ut/">Clearfield</a>
          <a href="/areas/roy-ut/">Roy</a>
          <a href="/areas/west-haven-ut/">West Haven</a>
          <a href="/areas/north-ogden-ut/">North Ogden</a>
          <span class="dropdown-group-label">Salt Lake County</span>
          <a href="/areas/salt-lake-city-ut/">Salt Lake City</a>
          <a href="/areas/south-jordan-ut/">South Jordan</a>
          <a href="/areas/sandy-ut/">Sandy</a>
          <span class="dropdown-group-label">Morgan County</span>
          <a href="/areas/morgan-ut/">Morgan</a>
          <a href="/areas/ogden-valley-ut/">Ogden Valley</a>
          <a href="/areas/" class="dropdown-view-all">View All Areas →</a>
        </div>
      </div>

      <a href="/our-team/" class="nav-link">Our Team</a>
      <a href="/blog/" class="nav-link">Blog</a>
      <a href="/financing/" class="nav-link">Financing</a>
      <a href="/contact/" class="nav-link">Contact</a>
      <a href="/get-quote/" class="nav-link nav-cta-btn">Get a Quote</a>
    </nav>

    <a href="tel:+18013970030" class="nav-phone">
      <i class="fas fa-phone" aria-hidden="true"></i>
      (801) 397-0030
    </a>

    <button class="mobile-menu-btn" aria-label="Toggle menu" aria-expanded="false">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
</header>
<!-- PARTIAL:nav:end -->

<nav class="breadcrumb-nav" aria-label="Breadcrumb">
  <div class="container">
    <ol class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><a href="/blog/">Blog</a></li>
      <li aria-current="page">{html.escape(title)}</li>
    </ol>
  </div>
</nav>

<section class="page-hero">
  <div class="container">
    <div class="page-hero-content">
      <h1>{html.escape(title)}</h1>
      <p class="hero-subtext">{html.escape(hero_subtext)}</p>
    </div>
  </div>
</section>

<div class="container">
  <img src="{image_url}" alt="{escape_attr(image_alt)}" style="width:100%;height:auto;display:block;border-radius:8px;margin-bottom:2rem;">
</div>

<main class="container" style="max-width:860px;">
  <article>
    <div class="article-byline" style="display:flex;align-items:center;gap:1rem;padding:1rem 0 2rem;border-bottom:1px solid #e5e7eb;margin-bottom:2rem;color:#6b7280;font-size:0.95rem;">
      <img src="/assets/images/logo-salmon.png" alt="Salmon HVAC" width="40" height="40" style="border-radius:50%;">
      <div>
        <strong style="color:#1a1a1a;">Salmon HVAC</strong><br>
        Published {human_date(published)} &nbsp;&bull;&nbsp; Updated {human_date(modified)} &nbsp;&bull;&nbsp; {read_time}
      </div>
    </div>

    <div class="article-content">
{body_html}
    </div>
  </article>
</main>

<!-- PARTIAL:cta:start -->
<section class="cta-section" aria-labelledby="cta-heading">
  <div class="container">
    <h2 id="cta-heading">Ready to Get Started?</h2>
    <p>Northern Utah's most trusted HVAC contractor is one call away. No overtime charges on weekdays.</p>
    <div class="cta-buttons">
      <a href="tel:+18013970030" class="btn btn-primary">
        <i class="fas fa-phone" aria-hidden="true"></i>
        Call (801) 397-0030
      </a>
      <a href="/get-quote/" class="btn btn-outline">
        Get a Free Quote
      </a>
      <a href="/financing/" class="btn btn-outline">
        <i class="fas fa-dollar-sign" aria-hidden="true"></i>
        Apply for Financing
      </a>
    </div>
    <div class="cta-trust-badges">
      <span><i class="fas fa-check-circle" aria-hidden="true"></i> 47 Years in Business</span>
      <span><i class="fas fa-check-circle" aria-hidden="true"></i> <a href="https://daikincomfort.com/" target="_blank" rel="noopener" class="daikin-link">Daikin</a> Comfort Pro Authorized</span>
      <span><i class="fas fa-check-circle" aria-hidden="true"></i> Licensed &amp; Insured</span>
    </div>
  </div>
</section>
<!-- PARTIAL:cta:end -->

<!-- PARTIAL:footer:start -->
<footer class="footer">
  <div class="container">
    <div class="footer-grid">
      <div class="footer-brand">
        <a href="/" class="logo">
          <img src="/assets/images/logo-salmon.png" alt="Salmon HVAC Logo" width="40" height="40">
          <span class="logo-text">Salmon <span>HVAC</span></span>
        </a>
        <p>Northern Utah's trusted HVAC professionals since 1979. Family-owned, community-focused, and committed to your comfort.</p>
      </div>

      <div class="footer-links-section">
        <h4>Services</h4>
        <ul class="footer-links">
          <li><a href="/services/ac-repair/">AC Repair</a></li>
          <li><a href="/services/ac-installation/">AC Installation</a></li>
          <li><a href="/services/ac-maintenance/">AC Maintenance</a></li>
          <li><a href="/services/furnace-repair/">Furnace Repair</a></li>
          <li><a href="/services/furnace-installation/">Furnace Installation</a></li>
          <li><a href="/services/heat-pump-services/">Heat Pump Services</a></li>
          <li><a href="/services/ductless-mini-split/">Ductless Mini-Split</a></li>
          <li><a href="/services/vrf-systems/">VRF Systems</a></li>
          <li><a href="/services/commercial-hvac/">Commercial HVAC</a></li>
          <li><a href="/services/indoor-air-quality/">Indoor Air Quality</a></li>
          <li><a href="/services/emergency-hvac/">Emergency HVAC</a></li>
        </ul>
      </div>

      <div class="footer-links-section">
        <h4>Service Areas</h4>
        <ul class="footer-links">
          <li><a href="/areas/centerville-ut/">Centerville, UT</a></li>
          <li><a href="/areas/bountiful-ut/">Bountiful, UT</a></li>
          <li><a href="/areas/layton-ut/">Layton, UT</a></li>
          <li><a href="/areas/kaysville-ut/">Kaysville, UT</a></li>
          <li><a href="/areas/farmington-ut/">Farmington, UT</a></li>
          <li><a href="/areas/fruit-heights-ut/">Fruit Heights, UT</a></li>
          <li><a href="/areas/ogden-ut/">Ogden, UT</a></li>
          <li><a href="/areas/clearfield-ut/">Clearfield, UT</a></li>
          <li><a href="/areas/roy-ut/">Roy, UT</a></li>
          <li><a href="/areas/west-haven-ut/">West Haven, UT</a></li>
          <li><a href="/areas/north-ogden-ut/">North Ogden, UT</a></li>
          <li><a href="/areas/salt-lake-city-ut/">Salt Lake City, UT</a></li>
          <li><a href="/areas/south-jordan-ut/">South Jordan, UT</a></li>
          <li><a href="/areas/sandy-ut/">Sandy, UT</a></li>
          <li><a href="/areas/morgan-ut/">Morgan, UT</a></li>
          <li><a href="/areas/ogden-valley-ut/">Ogden Valley, UT</a></li>
          <li><a href="/areas/">View All Areas</a></li>
        </ul>
      </div>

      <div class="footer-contact">
        <h4>Contact Us</h4>
        <div class="footer-contact-item">
          <i class="fas fa-paper-plane" aria-hidden="true"></i>
          <a href="/contact/">Send Us a Message</a>
        </div>
        <div class="footer-contact-item">
          <i class="fas fa-dollar-sign" aria-hidden="true"></i>
          <a href="/financing/">Apply for Financing</a>
        </div>
        <div class="footer-contact-item">
          <i class="fas fa-phone" aria-hidden="true"></i>
          <a href="tel:+18013970030">(801) 397-0030</a>
        </div>
        <div class="footer-contact-item">
          <i class="fas fa-envelope" aria-hidden="true"></i>
          <a href="mailto:office@salmonhvac.com">office@salmonhvac.com</a>
        </div>
        <div class="footer-contact-item">
          <i class="fas fa-map-marker-alt" aria-hidden="true"></i>
          <span>1265 W 1275 N #7, Centerville, UT 84014</span>
        </div>
        <div class="footer-contact-item">
          <i class="fas fa-clock" aria-hidden="true"></i>
          <div>
            <span>Mon–Fri: 7:00 AM–6:00 PM</span>
            <span class="footer-emergency-badge"><i class="fas fa-bolt" aria-hidden="true"></i> 24/7 Emergency Service</span>
          </div>
        </div>
        <div class="footer-social">
          <a href="https://www.facebook.com/SalmonHVAC" target="_blank" rel="noopener" aria-label="Salmon HVAC on Facebook">
            <i class="fab fa-facebook-f" aria-hidden="true"></i>
          </a>
          <a href="https://www.instagram.com/salmonhvac" target="_blank" rel="noopener" aria-label="Salmon HVAC on Instagram">
            <i class="fab fa-instagram" aria-hidden="true"></i>
          </a>
          <a href="https://g.page/salmonhvac" target="_blank" rel="noopener" aria-label="Salmon HVAC on Google">
            <i class="fab fa-google" aria-hidden="true"></i>
          </a>
        </div>
      </div>
    </div>

    <div class="footer-bottom">
      <p>&copy; 2026 Salmon HVAC LLC | Serving Northern Utah Since 1979</p>
      <div class="footer-legal-links">
        <a href="/privacy-policy/">Privacy Policy</a>
        <a href="/terms-of-service/">Terms of Service</a>
      </div>
    </div>
  </div>
</footer>
<!-- PARTIAL:footer:end -->

<script src="/assets/js/main.js?v=3"></script>
</body>
</html>
"""


def render_blog_card(post: dict) -> str:
    image = post["image"] or "/assets/images/logo-salmon.png"
    image_alt = escape_attr(post.get("imageAlt") or post["title"])
    title = html.escape(post["title"])
    excerpt = html.escape(post["excerpt"])
    url = post["url"]
    return f"""    <article class="blog-card">
      <div class="blog-card-image">
        <img src="{image}" alt="{image_alt}" width="400" height="250">
      </div>
      <div class="blog-card-content">
        <div style="font-size:0.85rem;color:#6b7280;margin-bottom:0.5rem;">{post['dateDisplay']} &nbsp;&bull;&nbsp; {post['readTime']}</div>
        <h2 style="font-size:1.15rem;"><a href="{url}">{title}</a></h2>
        <p>{excerpt}</p>
        <a href="{url}" class="read-more">Read the Full Guide <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
      </div>
    </article>"""


def update_blog_index(posts: List[dict]) -> None:
    html_text = BLOG_INDEX_PATH.read_text("utf-8")
    cards_markup = "\n\n".join(render_blog_card(post) for post in posts)
    replacement = f"""<!-- Blog Grid -->
<main class="container" style="padding-top:3rem;padding-bottom:4rem;">

  <div class="blog-grid">

{cards_markup}

  </div>
</main>"""
    updated = re.sub(
        r'<!-- Blog Grid -->[\s\S]*?</main>',
        replacement,
        html_text,
        count=1,
    )
    BLOG_INDEX_PATH.write_text(updated, "utf-8")


def normalize_imported_post(
    raw_post: dict,
    postmeta: Dict[int, Dict[str, List[object]]],
) -> Optional[dict]:
    slug = raw_post["post_name"].strip()
    if not slug:
        return None

    attachment_values = postmeta.get(int(raw_post["ID"]), {}).get("_thumbnail_id", [])
    attachment_id = int(attachment_values[0]) if attachment_values else None
    image_relative_path = wp_image_path_from_attachment(attachment_id, postmeta)
    image_url = copy_featured_image(image_relative_path)

    content_html = clean_html_content(raw_post["post_content"])
    excerpt = clean_text(raw_post["post_excerpt"]) or excerpt_from_content(content_html)
    if not excerpt:
        excerpt = clean_text(raw_post["post_title"])

    title = clean_text(raw_post["post_title"])
    image_alt = wp_image_alt(attachment_id, postmeta, title)
    published = iso_date(raw_post["post_date"])
    modified = iso_date(raw_post["post_modified"] or raw_post["post_date"])
    read_time = estimate_read_time(content_html)
    hero_subtext = excerpt

    return {
        "slug": slug,
        "title": title,
        "excerpt": excerpt,
        "content": content_html,
        "heroSubtext": hero_subtext,
        "image": image_url,
        "imageAlt": image_alt,
        "date": published,
        "modified": modified,
        "dateDisplay": human_date(published),
        "readTime": read_time,
        "url": f"/blog/{slug}/",
    }


def write_imported_post(post: dict) -> None:
    post_dir = BLOG_ROOT / post["slug"]
    post_dir.mkdir(parents=True, exist_ok=True)
    (post_dir / "index.html").write_text(render_post_html(post), "utf-8")


def sort_posts(posts: Iterable[dict]) -> List[dict]:
    return sorted(posts, key=lambda entry: (entry["date"], entry["title"].lower()), reverse=True)


def build_posts_json_entry(post: dict) -> dict:
    return {
        "title": post["title"],
        "excerpt": post["excerpt"],
        "url": post["url"],
        "image": post["image"] or "/assets/images/logo-salmon.png",
        "imageAlt": post["imageAlt"],
        "date": post["date"],
        "dateDisplay": post["dateDisplay"],
        "readTime": post["readTime"],
    }


def main() -> None:
    if not SQL_PATH.exists():
        raise SystemExit(f"Missing SQL dump at {SQL_PATH}")

    posts, postmeta = load_wordpress_data()
    authoritative_slugs = current_authoritative_slugs()
    current_posts = load_current_posts()

    published_wp_posts = [
        post
        for post in posts
        if post["post_type"] == "post" and post["post_status"] == "publish"
    ]

    imported_posts = []
    for raw_post in published_wp_posts:
        normalized = normalize_imported_post(raw_post, postmeta)
        if not normalized:
            continue
        if normalized["slug"] in authoritative_slugs:
            continue
        imported_posts.append(normalized)

    imported_posts = sort_posts(imported_posts)

    for post in imported_posts:
        write_imported_post(post)

    current_post_entries = []
    for slug, entry in current_posts.items():
        if slug not in authoritative_slugs:
            continue
        current_post_entries.append(
            {
                "slug": slug,
                "title": entry["title"],
                "excerpt": entry["excerpt"],
                "image": entry.get("image"),
                "imageAlt": entry.get("imageAlt") or entry["title"],
                "date": entry["date"],
                "dateDisplay": entry["dateDisplay"],
                "readTime": entry["readTime"],
                "url": entry["url"],
            }
        )

    merged_posts = sort_posts([*current_post_entries, *imported_posts])
    POSTS_JSON_PATH.write_text(
        json.dumps([build_posts_json_entry(post) for post in merged_posts], indent=2) + "\n",
        "utf-8",
    )
    update_blog_index(merged_posts)

    print(
        json.dumps(
            {
                "published_wp_posts": len(published_wp_posts),
                "imported_posts": len(imported_posts),
                "existing_authoritative_posts": len(authoritative_slugs),
                "merged_posts": len(merged_posts),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
